# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e514f6f2cfc36af67037b8ea7ed9cdaaa8d09016eaf8eeb2cb7b7069cee298a26da1ecdfa7230e455ed88dff05ddbbeec819beca4cdec041c2a1307c04f6a89e

test:
  secret_key_base: aaa5b3678c4cd20ab4e4fda3df96af35eb73b1940c1ac7eb1b728fa3c9275736e2a9edbbe903236008ccf25e030d85b86cea7696888c441ead3c979701a1d329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
